//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int ad_id { get; set; }
        public string ad_firstname { get; set; }
        public string ad_lastname { get; set; }
        public string ad_gmail { get; set; }
        public string ad_pass { get; set; }
        public string ad_img { get; set; }
    }
}
