//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.user_cart = new HashSet<user_cart>();
            this.user_wait = new HashSet<user_wait>();
        }
    
        public string co_id { get; set; }
        public string co_name { get; set; }
        public string co_teacher { get; set; }
        public Nullable<System.DateTime> co_startday { get; set; }
        public Nullable<System.DateTime> co_endday { get; set; }
        public string co_des { get; set; }
        public Nullable<int> co_price { get; set; }
        public string co_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_cart> user_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_wait> user_wait { get; set; }
    }
}
